name: plasticity Docs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v2

    - name: 'Update apt'
      run: sudo apt update

    - name: 'Install Eigen3'
      run: sudo apt install libeigen3-dev

    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install plasticity
      run: |
        python setup.py develop --user

    - name: Install docs dependencies
      run: |
        python -m pip install -r docs/requirements.txt

    - name: Install Doxygen
      run: |
        sudo apt install doxygen

    - name: 'Configure build'
      run: |
        mkdir buildDirectory_debug
        cd buildDirectory_debug
        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" -DBUILD_DOCS=ON
        cd ..
        mkdir buildDirectory_release
        cd buildDirectory_release
        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DBUILD_DOCS=ON
        cd ..

    - name: 'Build'
      run: |
        cd buildDirectory_debug
        cmake --build . --target install -- -j8
        cd ..
        cd buildDirectory_release
        cmake --build . --target install -- -j8
        cd ..

    - name: Build Python API
      run: |
        cd docs
        make html
        cd ..
